export const CREATE_TODO = "CREATE_TODO";
export const RETRIEVE_TODOS = "RETRIEVE_TODOS";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const COMPLETED_TODOS = "COMPLETED_TODOS";
export const UNCOMPLETED_TODOS = "UNCOMPLETED_TODOS";
